"""Rollout sampling, teacher-forced scoring, and training-array packing."""

from __future__ import annotations

from dataclasses import dataclass, field

import mlx.core as mx
import numpy as np
from mlx_lm.generate import generate_step
from mlx_lm.sample_utils import make_sampler

from .grpo import token_logprobs


@dataclass
class Rollout:
    prompt_tokens: list[int]
    completion_tokens: list[int]
    sampling_logprobs: list[float]  # model logprob of each sampled token
    text: str
    reward: float = 0.0
    reward_parts: dict = field(default_factory=dict)
    meta: dict = field(default_factory=dict)
    sage: bool = False  # generated by SAGE decoding (hybrid rollout groups)
    think_len: int | None = None  # tokens up to end-of-thinking (SAGE only)
    finish: str | None = None  # 'stop' | 'length' (truncation monitor)


def eos_ids(tokenizer) -> set[int]:
    ids = getattr(tokenizer, "eos_token_ids", None)
    if ids:
        return set(ids)
    return {tokenizer.eos_token_id}


def encode_prompt(tokenizer, messages: list[dict], **chat_kwargs) -> list[int]:
    return tokenizer.apply_chat_template(
        messages, add_generation_prompt=True, **chat_kwargs
    )


def sample_completion(
    model, tokenizer, prompt_ids: list[int], max_new_tokens: int, temperature: float
) -> tuple[list[int], list[float], str]:
    """Sample one completion; returns (tokens incl. EOS, per-token logprobs, text).

    The recorded logprob is the model's own (pre-sampler) log-softmax at the
    sampled token — the policy logprob used as old_lp in the ratio.
    """
    sampler = make_sampler(temp=temperature)
    stop = eos_ids(tokenizer)
    toks: list[int] = []
    lps: list[float] = []
    for token, logprobs in generate_step(
        mx.array(prompt_ids), model, max_tokens=max_new_tokens, sampler=sampler
    ):
        t = int(token)
        toks.append(t)
        lps.append(float(logprobs[t]))
        if t in stop:
            break
    text_toks = toks[:-1] if toks and toks[-1] in stop else toks
    return toks, lps, tokenizer.decode(text_toks)


def build_training_arrays(rollouts: list[Rollout], pad_id: int):
    """Right-pad [prompt+completion] sequences into next-token-prediction form.

    Returns numpy arrays inp [B, L-1], tgt [B, L-1], mask [B, L-1] (1.0 on
    completion targets), old_lp [B, L-1] aligned to tgt.
    """
    seqs = [r.prompt_tokens + r.completion_tokens for r in rollouts]
    B = len(seqs)
    L = max(len(s) for s in seqs)
    tokens = np.full((B, L), pad_id, dtype=np.int64)
    mask = np.zeros((B, L - 1), dtype=np.float32)
    old_lp = np.zeros((B, L - 1), dtype=np.float32)
    for i, (r, s) in enumerate(zip(rollouts, seqs)):
        tokens[i, : len(s)] = s
        pl, cl = len(r.prompt_tokens), len(r.completion_tokens)
        # target position j predicts token j+1: completion targets start at pl-1
        mask[i, pl - 1 : pl - 1 + cl] = 1.0
        old_lp[i, pl - 1 : pl - 1 + cl] = r.sampling_logprobs
    return tokens[:, :-1], tokens[:, 1:], mask, old_lp


def gather_selected(mask, tgt, old_lp, ref_lp, lo, hi):
    """Compress a microbatch slice [lo:hi] to its mask==1 positions.

    Returns (sel_idx [b, K], sel_mask [b, K], tgt/old_lp/ref_lp gathered),
    K = the slice's longest selection, shorter rows right-padded with
    index 0 under sel_mask 0 (the objective's mask gating makes padded
    positions contribute exactly nothing, garbage logprobs included).
    """
    rows = [np.flatnonzero(mask[i]) for i in range(lo, hi)]
    K = max(1, max((len(r) for r in rows), default=1))
    idx = np.zeros((len(rows), K), dtype=np.int64)
    sel_mask = np.zeros((len(rows), K), dtype=np.float32)
    for j, r in enumerate(rows):
        idx[j, : len(r)] = r
        sel_mask[j, : len(r)] = 1.0
    take = lambda a: np.take_along_axis(a[lo:hi], idx, axis=1)
    return idx, sel_mask, take(tgt), take(old_lp), take(ref_lp)


def score_logprobs(model, inp: np.ndarray, tgt: np.ndarray) -> np.ndarray:
    """Teacher-forced per-token logprobs for one (already padded) microbatch.

    Call under `adapters_disabled(model)` to score the reference policy.
    """
    # astype: bf16 arrays don't support the numpy buffer protocol
    lp = token_logprobs(model(mx.array(inp)), mx.array(tgt)).astype(mx.float32)
    mx.eval(lp)
    return np.array(lp)
